# Generated by Django 5.0.2 on 2024-06-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_buyer_order_user_cart_quantity_cart_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('course', models.TextField(max_length=100)),
            ],
        ),
    ]
